### ISSUE TITLE
【ご連絡】strConv.h がバージョンアップしました

### ISSUE THREAD

**Issue by javacommons** [towawot/AutoHarvestSE#1]
https://qiita.com/javacommons/items/9ea0c8fd43b61b01a8da の strConv.h をお使いいただきありがとうございます。
2019/02/27 23:23 に記事内の strconv.h を修正しました。「関数が使われてない」旨の警告メッセージがコンパイル時に出るのを解消するために、以下の関数を全て inline にしました。

std::wstring ansi_to_wide(const std::string &s)
std::string wide_to_ansi(const std::wstring &s)
std::wstring sjis_to_wide(const std::string &s)
std::string wide_to_sjis(const std::wstring &s)
std::wstring utf8_to_wide(const std::string &s)
std::string wide_to_utf8(const std::wstring &s)
std::string ansi_to_utf8(const std::string &s)
std::string utf8_to_ansi(const std::string &s)
std::string sjis_to_utf8(const std::string &s)
std::string utf8_to_sjis(const std::string &s)

機能的には変わりわないので、無理に差し替えなくても結構ですが一応ご連絡いたします。

**Comment by towawot** [comment]
初心者ゆえ文字コードとか分からず試行錯誤していた時にstrConv.hを検索で見つけてすごく助かりました :)
貴重なライブラリのシェアとアプデのご連絡まで…本当にありがとうございました
すぐには無理ですが何か変更をする際にあわせて差し替えたいと思います

**Comment by javacommons** [comment]
了解しました。strConv.h を使っていただきありがとうございます。
